### ISSUE TITLE
Status code 500 instead of 404 for Rack not found

### ISSUE THREAD

**Issue by jistr** [tuskar/tuskar#18]
When I try to fetch a rack with an id that doesn't belong to an existing rack (issue a GET request on `/v1/racks/123`), the server returns `500 Internal Server Error`. I'd expect `404 Not Found`.

**Comment by mfojtik** [comment]
@jistr thanks for reporting this. I am able to reproduce this, however it is not entirely clear right now what is going on here to me. I can see the exception class 'RackNotFound' defined properly in exceptions.py:

``` python
class RackNotFound(NotFound):
    message = _("Rack %(rack)s could not be found.")
```

The 'NotFound' parent class should set the HTTP response code to 404, but for some reason this does not work. I'll do further investigation tomorrow...

@markmc any ideas what could be possibly wrong?

**Comment by mfojtik** [comment]
K, I found this:

https://github.com/openstack/ceilometer/blob/master/ceilometer/api/controllers/v2.py#L885

``` python
        # FIXME (flwang): Need to change this to return a 404 error code when
        # we get a release of WSME that supports it.
        if len(alarms) < 1:
            raise wsme.exc.ClientSideError(_("Unknown alarm"))
```

So, it seems like WSME/Pecan does not support raising an '404' error? In this case, we will need to temporarily raise the ClientSideError or instead of raising an exception from `get_one` when the record is not found in database, return `nil` and then add check to the `get_one` method for `nil` and return 404 using `abort(404)` 

@marios @mtaylor thoughts ?

**Comment by marios** [comment]
@mfojtik - sure - abort(404) is way to go. I wonder if we could also just explicitly set status code like you do in https://github.com/tuskar/tuskar/blob/master/tuskar/api/controllers/v1.py#L220

```
 pecan.response.status_code = 201
```

**Comment by mfojtik** [comment]
@marios I tried that and also `abort(404)` but neither way works :-( currently i'm out of ideas.... it seems like that in ceilometer they return 400 instead of 404 (as stated in the comment above). My guess is that we should do the same with the same comment.

@markmc any ideas?

**Comment by jguiditta** [comment]
Wow, that would be pretty poor on pecan's part if it didn't support something as standard as a 404

**Comment by mfojtik** [comment]
OK, I managed to get this working and report 404:

``` python

    @wsme_pecan.wsexpose(Rack, unicode)
    def get_one(self, rack_id):
        """Retrieve information about the given Rack."""
        rack = pecan.request.dbapi.get_rack(rack_id)
        if not rack:
            pecan.response.status_code = 404
        else:
            links = [_make_link('self', pecan.request.host_url, 'racks',
                    rack.id)]
            return Rack.convert_with_links(rack, links)
```

I don't really like this solution. First off the JSON/XML response is wrong `<result nil="true">` (wth?), second this will make the actions looks more uglier. I'm pretty much liked the exception approach, hopefully it is something that can be fixed by fiddling some setting.

**Comment by jguiditta** [comment]
Ok, I don't have this totally figured out yet, but after quite a bit of digging about, it appears you are on the right track above.  From what I can tell, we have this wsmeext lib that we depend on, which overrides the expose method of pecan.  This in turn sets a return status code, in fact almost exactly as you try above in the controller code.  However, it has this funky little chunk in it:

``` python
if data['faultcode'] == 'Client':
    pecan.response.status = 400
else:
    pecan.response.status = 500
return data
```

This would explain the comment/error you found earlier about raising wsme.exc.ClientSideError.  Fwiw, this code is in tuskar/.tox/venv/lib/python2.7/site-packages/wsmeext/pecan.py in your dev setup.  Changing the above status default to 404 has the expected result:

```
< HTTP/1.0 404 Not Found
```

Also notice that in the base TuskarException class, the docstring explicitly only says anything about setting the message, NOT the error code, which I am pretty sure will work in no case, meaning we have had a false sense of being able to set/create errors of any usefulness.  I think that if we were to alter this exception handling in wsmeext.pecan::callfunction, we could find the right place to pass up a reasonable code (which we currently do not do).  However, as this is a dependency, I am not sure the best way to fix it, or if the upstream would even have an interest (havent looked who upstream even is just yet).  I wonder how critical this extenstion even is?  Anyway, I am confident this is the source of why errors don't do what they should, but am not yet sure how it should be fixed.  Will update with more if I find anything.

**Comment by mfojtik** [comment]
@jguiditta thanks a lot for this investigation! so it seems like the bug is on the wsme side. I think for now, we should patch this in our code using the way I described in comment above with a huge FIXME :-)

**Comment by mfojtik** [comment]
@jguiditta so even with my 'workaround', it does not work correctly. Pecan is expecting the 'Rack' object to be returned from the action, but in case when you request non-existing Rack, there is nothing to return... This leads to this error:

```
AttributeError: 'NoneType' object has no attribute 'capacities'
```

(see the pull request above)

Now I really don't have any clue how to fix this.... I think we will need to consider the Ceilometer approach with returning 'ClientError' (400) or, we can fix this in the upstream lib as you described.

**Comment by slagle** [comment]
There is some support for this in the wsme+pecan extension now in the latest wsme in bitbucket, but it has not made it into a release yet.

This commit is what is relevant:
https://bitbucket.org/cdevienne/wsme/diff/wsmeext/pecan.py?diff2=104cc7f45dc4
So, you could do something like the following in the controller method and it would work (however you won't get an Error object returned):

``` python
return wsme.api.Response(Rack(), status_code=404)
```

I also emailed the wsme upstream google group to see if there are any plans for supporting this a little better.

Another possibility to add support for different status codes is writing our own JSonRenderer class in tuskar and replacing the one that wsmeext.pecan installs.  This approach is a bit hack'ish...but it could solve the problem without having to modify wsme (or wsmeext).

This code would look rougly like:

``` python
class JSonRenderer(object):
    def __init__(self, path, extra_vars):
        pass

    def render(self, template_path, namespace):
        import json
        from wsme.api import Response
        result = namespace['result']
        if isinstance(namespace['result'], Response):
            pecan.response.status_code = result.status_code
            # Return whatever we want here...
            return json.dumps({'faultstring':'Rack Not Found'})

        if 'faultcode' in namespace:
            return wsme.rest.json.encode_error(None, namespace)
        return wsme.rest.json.encode_result(
            namespace['result'],
            namespace['datatype']
        )

pecan.templating._builtin_renderers['wsmejson'] = JSonRenderer
```

Then, if the controller method (such as get_one) returns a Response with 404 set, the correct thing gets sent to the client.  We could also add support to handle all different types of unexpected status codes.

**Comment by jguiditta** [comment]
I actually think a variation of this would not be hackish, and if proper support were to be added in wsme, we could later toss any decorator style code we may have added for our own needs.  We have real error objects already, so perhaps we could just pass them into this renderer instead of having to have a separate render for each error type? This is again along the line I was asking you about more generically Friday. So, it would be something like (pseudo-code coming):

``` python
return wsme.api.Response(Rack(), error=e)
```

and then the renderer would take that error object and extract whatever the code and message is.

**Comment by slagle** [comment]
Yes, that's along the lines of what I was thinking.  If you look at that sample JsonRenderer class I put in the earlier comment, that could be modified to handle different response types.  So, it would just be the one JsonRenderer class.

**Comment by jguiditta** [comment]
Agreed, my vote is for pursuing this path, at least for now. I'll start tinkering with your example renderer and see if I can get it working here shortly

**Comment by jguiditta** [comment]
Closing, as this has been resolved for some time now, we just forgot to close the related issue
