### ISSUE TITLE
Curl samples how to trigger provisioning of the data center

### ISSUE THREAD

**Issue by jistr** [tuskar/tuskar#48]
We want to trigger the provisioning from tuskarclient. We could use some documentation on how to do that via Tuskar's API.

**Comment by mfojtik** [comment]
It's is simple:

`POST /v1/data_centers/`

Should start provisioning the DataCenter. You should get back JSON representation of the Heat 'stack' with links pointing to the Heat, so in future you can check this for status updates.

Also `GET /v1/data_centers` will give you the JSON representation of the Heat stack, with the current provisioning status.

Note that the Rack 'state' machine looks now like:
1. 'unprovisioned'
2. 'provisioning'
3. 'provisioned'
   (4. 'error')

The Racks state is updated automatically, right after the Heat stack state changes.

**Comment by mfojtik** [comment]
Closing this issue as it seems to be fixed now:

https://github.com/tuskar/python-tuskarclient/pull/14

Thanks @jistr !
