### ISSUE TITLE
set flavors for resource class

### ISSUE THREAD

**Issue by jprovaznik** [tuskar/tuskar#50]
This task is not urgent.

It would be handy (from UI POV) to use  PUT /api/resource_class/1  to update set of rclass flavors (as it's possible with racks).

provazn> marios: when updating a resource class, a user sets new set of flavors too. So if you would choose " POST /api/resource_class/1/flavors", I would have to 1) delete all existing flavors one by one, 2) add new flavors in one POST request, right? In opposite, by using PUT /api/resource_class/1 I can call one API call

**Comment by marios** [comment]
should be addressed by https://github.com/tuskar/tuskar/pull/92 - testing please

**Comment by marios** [comment]
merged #92 so closing ticket
