### ISSUE TITLE
incomplete list of resource classes is returned

### ISSUE THREAD

**Issue by jprovaznik** [tuskar/tuskar#57]
If I load sample data, I have following records in tuskar db:
sqlite> select \* from resource_classes;
1|compute-rc|compute|2013-07-24 10:49:14.686786|
2|non-compute-rc|not_compute|2013-07-24 10:49:14.799393|

But API returns only one rclass:
$ curl -v -X GET -H 'Accept: application/json' http://0.0.0.0:6385/v1/resource_classes 
- About to connect() to 0.0.0.0 port 6385 (#0)
-   Trying 0.0.0.0...
- connected
- Connected to 0.0.0.0 (0.0.0.0) port 6385 (#0)
  > GET /v1/resource_classes HTTP/1.1
  > User-Agent: curl/7.27.0
  > Host: 0.0.0.0:6385
  > Accept: application/json
  > 
- HTTP 1.0, assume close after body
  < HTTP/1.0 200 OK
  < Date: Wed, 24 Jul 2013 11:06:27 GMT
  < Server: WSGIServer/0.1 Python/2.7.3
  < Content-Length: 888
  < Content-Type: application/json; charset=UTF-8
  < 
- Closing connection #0
  [{"flavors": [{"capacities": [{"value": "4", "name": "cpu", "unit": "count"}, {"value": "15", "name": "memory", "unit": "GB"}, {"value": "1680", "name": "storage", "unit": "GB"}], "max_vms": null, "id": 1, "links": [{"href": "http://0.0.0.0:6385/v1/resource_classes/1/flavors/1", "rel": "self"}], "name": "m1.xlarge"}], "name": "compute-rc", "links": [{"href": "http://0.0.0.0:6385/v1/resource_classes/1", "rel": "self"}], "id": 1, "service_type": "compute", "racks": [{"id": 1, "links": [{"href": "http://0.0.0.0:6385/v1/racks/1", "rel": "self"}]}, {"id": 2, "links": [{"href": "http://0.0.0.0:6385/v1/racks/2", "rel": "self"}]}]}, {"flavors": [], "name": "non-compute-rc", "links": [{"href": "http://0.0.0.0:6385/v1/resource_classes/2", "rel": "self"}], "id": 2, "service_type": "not_compute", "racks": [{"id": 3, "links": [{"href": "http://0.0.0.0:6385/v1/racks/3", "rel": "self"}]}]}]

THis is most probably a regression caused by pep8 patch from yesterday.

**Comment by mfojtik** [comment]
This is fixed here: https://github.com/tuskar/tuskar/commit/ce2d74da4cf33adc807226623ebaee7d50a93f0a

Can you please confirm?

**Comment by jprovaznik** [comment]
Works for me now.
