### ISSUE TITLE
sample_dat for demo purposes

### ISSUE THREAD

**Issue by jcoufal** [tuskar/tuskar#58]
There is need for different sample_data for UI demonstration.
##### Classes:

... only one predefined resource class (m1), which should copy the same what OpenStack currently provides
- "m1", compute, contains following flavors (m1.tiny, m1.small, m1.medium, m1.large, m1.xlarge), contains 2+ racks (can be more, no preference)
##### Nodes:

... Can stay the same, just name the nodes with their MACs
##### Racks:

... Can stay the same, but name the racks little bit better so they indicate that it is a rack, 'compute' / 'non_compute' can be confusing. Furthermore, we are not going to deal with non-computes for demo purposes at all.
... Update statuses to have some OK and some Error racks

**Comment by jcoufal** [comment]
After call with Martyn and Marios - update:

##### Classes:
- 'm1'... as described before
- 'r1 - core services'... the non-compute type, containing all the core services

##### Racks:
- 2 racks, one for each resource class

##### Nodes:
- One in 'm1' associated rack
- Second in 'r1 - core services'
- Third in unracked (not associated in any rack)

**Comment by jistr** [comment]
Closing, it's no longer relevant.
