### ISSUE TITLE
Unit in Rack's Capacities

### ISSUE THREAD

**Issue by jtomasek** [tuskar/tuskar#72]
Right now, rack's capacities return only name and value, capacity should also include a 'unit'. This is probably easily fixed by adding 'unit' to tools/sample_data.py

**Comment by mfojtik** [comment]
Hmm looking at the sample script:

```
    capacities = [
        dict(name='total_cpu', value='64', unit='count'),
        dict(name='total_memory', value='16384', unit='MB'),
    ]
```

It seems the units are there, going to check the code.

**Comment by mfojtik** [comment]
Should be fixed in the pull request above... You just need to rerun the setup_data.py script ;-) (and reset the DB)
