### ISSUE TITLE
POST to /v1/data_centers/ requires the trailing slash

### ISSUE THREAD

**Issue by jistr** [tuskar/tuskar#91]
`POST /v1/data_centers/` triggers the data center provisioning, but
`POST /v1/data_centers` doesn't trigger the data center provisioning.

**Comment by marios** [comment]
Hey @jistr - I can't recreate this. Both:

```
curl -X POST -H "Accept: application/json" http://0.0.0.0:6385/v1/data_centers
```

AND

```
curl -X POST -H "Accept: application/json" http://0.0.0.0:6385/v1/data_centers/
```

hit the target. I put a pdb.set_trace() at the top of the POST route:

```
501     def post(self):$                                                       
502         import pdb; pdb.set_trace()$
```

and the route was hit both times. Do I need to do something else to recreate?

thanks, marios

**Comment by jistr** [comment]
Ah then it had to be silently fixed in the meantime. It didn't work when i was implementing the client code. (I did exactly the same thing with pdb as you did.) Then I can remove the hack from tuskarclient.

Thanks for looking at this @marios :)
